spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      jdbc-url: jdbc:mysql://192.168.100.167:3306/nh80db?characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: izex_0329
      driver-class-name: org.mariadb.jdbc.Driver
      pool-name: hikari-cp
      maximum-pool-size: 100
      minimum-idle: 2
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

server:
  servlet:
    register-default-servlet: true
  port: 11040

graphql:
  spqr:
    gui:
      enabled: false
